# Generated by Django 4.2.7 on 2026-07-27 19:15

from django.db import migrations, models


def fold_retired_types(apps, schema_editor):
    """Attendance is now Present/Absent only. Fold any legacy rows:
    late  -> present (they already counted as present, is_present=True)
    leave -> absent  (they already counted as absent,  is_present=False)."""
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')
    AttendanceRecord.objects.filter(attendance_type='late').update(
        attendance_type='present', is_present=True
    )
    AttendanceRecord.objects.filter(attendance_type='leave').update(
        attendance_type='absent', is_present=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_attendance_type'),
    ]

    operations = [
        migrations.RunPython(fold_retired_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], default='', max_length=10),
        ),
    ]
