# Generated by Django 4.2.7 on 2026-07-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_routines', '0003_semesterarchive_and_more'),
        ('attendance', '0005_alter_attendancerecord_attendance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='class_routines.semesterarchive'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['archive'], name='attendance__archive_344e77_idx'),
        ),
    ]
