# Generated by Django 5.1.4 on 2026-02-10 19:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('students', '0002_add_nationality_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StipendCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Criteria name (e.g., 'Semester 4 Stipend 2024')", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('minAttendance', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum attendance percentage required', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minGpa', models.DecimalField(decimal_places=2, default=2.5, help_text='Minimum GPA required', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('passRequirement', models.CharField(choices=[('all_pass', 'All Subjects Pass'), ('1_referred', 'Max 1 Referred'), ('2_referred', 'Max 2 Referred'), ('any', 'Any (No Restriction)')], default='all_pass', help_text='Pass requirement for eligibility', max_length=20)),
                ('semester', models.IntegerField(blank=True, help_text='Specific semester (leave blank for all)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('shift', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Evening', 'Evening')], help_text='Specific shift (leave blank for all)', max_length=20, null=True)),
                ('session', models.CharField(blank=True, help_text='Specific session (leave blank for all)', max_length=20, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stipend_criteria', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Specific department (leave blank for all)', null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'verbose_name': 'Stipend Criteria',
                'verbose_name_plural': 'Stipend Criteria',
                'db_table': 'stipend_criteria',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='StipendEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('referredSubjects', models.IntegerField(default=0)),
                ('totalSubjects', models.IntegerField(default=0)),
                ('passedSubjects', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('isEligible', models.BooleanField(default=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('approvedAt', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stipends', to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_students', to='stipends.stipendcriteria')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stipend_eligibilities', to='students.student')),
            ],
            options={
                'verbose_name': 'Stipend Eligibility',
                'verbose_name_plural': 'Stipend Eligibilities',
                'db_table': 'stipend_eligibility',
                'ordering': ['rank', '-gpa', '-attendance'],
                'unique_together': {('student', 'criteria')},
            },
        ),
    ]
