# Generated by Django 4.2.7 on 2026-07-01 22:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stipends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StipendCriteriaSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minAttendance', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minGpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('passRequirement', models.CharField(choices=[('all_pass', 'All Subjects Pass'), ('1_referred', 'Max 1 Referred'), ('2_referred', 'Max 2 Referred'), ('any', 'Any (No Restriction)')], default='all_pass', max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stipend_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stipend Criteria Settings',
                'verbose_name_plural': 'Stipend Criteria Settings',
                'db_table': 'stipend_criteria_settings',
            },
        ),
    ]
