# Generated by Django 4.2.7 on 2025-12-01 19:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullNameBangla', models.CharField(max_length=255)),
                ('fullNameEnglish', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('fatherNID', models.CharField(max_length=20)),
                ('motherName', models.CharField(max_length=255)),
                ('motherNID', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField()),
                ('birthCertificateNo', models.CharField(max_length=50)),
                ('nidNumber', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('bloodGroup', models.CharField(blank=True, max_length=5)),
                ('maritalStatus', models.CharField(blank=True, max_length=20)),
                ('mobileStudent', models.CharField(max_length=11)),
                ('guardianMobile', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergencyContact', models.CharField(max_length=255)),
                ('presentAddress', models.JSONField()),
                ('permanentAddress', models.JSONField()),
                ('highestExam', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=50)),
                ('rollNumber', models.CharField(max_length=50)),
                ('registrationNumber', models.CharField(max_length=50)),
                ('passingYear', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('institutionName', models.CharField(blank=True, max_length=255)),
                ('currentRollNumber', models.CharField(max_length=50, unique=True)),
                ('currentRegistrationNumber', models.CharField(max_length=50, unique=True)),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('session', models.CharField(max_length=20)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Evening', 'Evening')], max_length=20)),
                ('currentGroup', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('enrollmentDate', models.DateField()),
                ('semesterResults', models.JSONField(blank=True, default=list)),
                ('semesterAttendance', models.JSONField(blank=True, default=list)),
                ('discontinuedReason', models.TextField(blank=True)),
                ('lastSemester', models.IntegerField(blank=True, null=True)),
                ('profilePhoto', models.CharField(blank=True, max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['currentRollNumber'], name='students_current_84d047_idx'), models.Index(fields=['currentRegistrationNumber'], name='students_current_4be092_idx'), models.Index(fields=['status'], name='students_status_3ac771_idx'), models.Index(fields=['department', 'semester'], name='students_departm_f1d848_idx')],
            },
        ),
    ]
