# Generated by Django 4.2.7 on 2026-07-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_birthcertificateno_alter_student_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='finalCgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
