# Generated by Django 4.2.7 on 2026-07-20 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_student_finalcgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('purge_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Deletion'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_student_deletions', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Deletion Request',
                'verbose_name_plural': 'Student Deletion Requests',
                'db_table': 'student_deletion_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'purge_at'], name='student_del_status_b1527f_idx'), models.Index(fields=['user_id'], name='student_del_user_id_52b34a_idx')],
            },
        ),
    ]
