# Generated by Django 4.2.7 on 2026-07-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='publicProfileEnabled',
            field=models.BooleanField(blank=True, help_text='Explicit public-profile choice; NULL = gender-based default (off for female students, on otherwise)', null=True),
        ),
    ]
