# Generated by Django 4.2.7 on 2025-12-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("current_value", models.TextField()),
                ("requested_value", models.TextField()),
                ("reason", models.TextField()),
                ("supporting_documents", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_requests",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correction Request",
                "verbose_name_plural": "Correction Requests",
                "db_table": "correction_requests",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="correction__student_e83234_idx",
                    ),
                    models.Index(
                        fields=["status"], name="correction__status_da95cb_idx"
                    ),
                    models.Index(
                        fields=["submitted_at"], name="correction__submitt_e16c9f_idx"
                    ),
                ],
            },
        ),
    ]
