# Generated by Django 4.2.7 on 2025-12-08 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teachers", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("adminNotes", models.TextField(blank=True)),
                ("resolvedDate", models.DateTimeField(blank=True, null=True)),
                ("requestDate", models.DateTimeField(auto_now_add=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_requests",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Request",
                "verbose_name_plural": "Teacher Requests",
                "db_table": "teacher_requests",
                "ordering": ["-requestDate"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="teacher_req_status_bfd19c_idx"
                    ),
                    models.Index(
                        fields=["requestDate"], name="teacher_req_request_c6da29_idx"
                    ),
                    models.Index(
                        fields=["teacher"], name="teacher_req_teacher_b0bd31_idx"
                    ),
                    models.Index(
                        fields=["student"], name="teacher_req_student_c6767e_idx"
                    ),
                ],
            },
        ),
    ]
