# Generated by Django 4.2.7 on 2025-12-08 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departments", "0001_initial"),
        ("teacher_requests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherSignupRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name_bangla", models.CharField(max_length=255)),
                ("full_name_english", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile_number", models.CharField(max_length=11)),
                ("designation", models.CharField(max_length=100)),
                ("qualifications", models.JSONField(default=list)),
                ("specializations", models.JSONField(default=list)),
                ("office_location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="departments.department",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_teacher_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_signup_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Signup Request",
                "verbose_name_plural": "Teacher Signup Requests",
                "db_table": "teacher_signup_requests",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="teacher_sig_status_824192_idx"
                    ),
                    models.Index(fields=["email"], name="teacher_sig_email_62cce8_idx"),
                    models.Index(
                        fields=["submitted_at"], name="teacher_sig_submitt_8393e8_idx"
                    ),
                ],
            },
        ),
    ]
