# Generated by Django 4.2.7 on 2026-06-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_add_department_fields'),
        ('teacher_requests', '0002_teachersignuprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersignuprequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department'),
        ),
    ]
