# Generated by Django 4.2.7 on 2025-12-09 16:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teachers", "0001_initial"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassRoutine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ]
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Day", "Day"),
                            ("Evening", "Evening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session", models.CharField(max_length=20)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("subject_name", models.CharField(max_length=255)),
                ("subject_code", models.CharField(max_length=50)),
                ("room_number", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_routines",
                        to="departments.department",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_routines",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Routine",
                "verbose_name_plural": "Class Routines",
                "db_table": "class_routines",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["department", "semester", "shift"],
                        name="class_routi_departm_c58057_idx",
                    ),
                    models.Index(
                        fields=["teacher"], name="class_routi_teacher_42ea6f_idx"
                    ),
                    models.Index(
                        fields=["day_of_week", "start_time"],
                        name="class_routi_day_of__e954bc_idx",
                    ),
                ],
            },
        ),
    ]
