# Generated by Django 4.2.7 on 2026-07-28 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_routines', '0002_add_class_type_lab_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('session', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('routines_count', models.IntegerField(default=0)),
                ('attendance_count', models.IntegerField(default=0)),
                ('marks_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Semester Archive',
                'verbose_name_plural': 'Semester Archives',
                'db_table': 'semester_archives',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.AddField(
            model_name='semesterarchive',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_archives', to=settings.AUTH_USER_MODEL),
        ),
        # The field must exist before an index can reference it (the
        # autogenerated order put AddIndex first, which fails).
        migrations.AddField(
            model_name='classroutine',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='class_routines.semesterarchive'),
        ),
        migrations.AddIndex(
            model_name='classroutine',
            index=models.Index(fields=['archive'], name='class_routi_archive_43b8e3_idx'),
        ),
    ]
