# Generated by Django 4.2.7 on 2025-12-08 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name_bangla", models.CharField(max_length=255)),
                ("full_name_english", models.CharField(max_length=255)),
                ("father_name", models.CharField(max_length=255)),
                ("father_nid", models.CharField(max_length=20)),
                ("mother_name", models.CharField(max_length=255)),
                ("mother_nid", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("birth_certificate_no", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("religion", models.CharField(blank=True, max_length=50)),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("mobile_student", models.CharField(max_length=11)),
                ("guardian_mobile", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("emergency_contact", models.CharField(max_length=255)),
                ("present_address", models.JSONField()),
                ("permanent_address", models.JSONField()),
                ("highest_exam", models.CharField(max_length=100)),
                ("board", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=50)),
                ("roll_number", models.CharField(max_length=50)),
                ("registration_number", models.CharField(max_length=50)),
                ("passing_year", models.IntegerField()),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=4)),
                ("institution_name", models.CharField(blank=True, max_length=255)),
                (
                    "desired_shift",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Day", "Day"),
                            ("Evening", "Evening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session", models.CharField(max_length=20)),
                ("documents", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "desired_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission_requests",
                        to="departments.department",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_admissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission",
                "verbose_name_plural": "Admissions",
                "db_table": "admissions",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="admissions_status_148dd5_idx"
                    ),
                    models.Index(
                        fields=["desired_department"],
                        name="admissions_desired_713f35_idx",
                    ),
                    models.Index(
                        fields=["submitted_at"], name="admissions_submitt_a35be3_idx"
                    ),
                    models.Index(
                        fields=["session"], name="admissions_session_de6836_idx"
                    ),
                ],
            },
        ),
    ]
