# Generated by Django 4.2.7 on 2025-12-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0001_initial"),
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="desired_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admission_requests",
                to="departments.department",
            ),
        ),
    ]
