# Generated by Django 4.2.7 on 2025-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0002_alter_admission_desired_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="draft_data",
            field=models.JSONField(
                blank=True,
                help_text="Stores incomplete form data for drafts",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="draft_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time draft was updated", null=True
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="is_draft",
            field=models.BooleanField(
                default=False, help_text="True if this is a draft, False if submitted"
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="birth_certificate_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="admission",
            name="board",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="admission",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="admission",
            name="desired_shift",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Morning", "Morning"),
                    ("Day", "Day"),
                    ("Evening", "Evening"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="admission",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="admission",
            name="father_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="admission",
            name="father_nid",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="admission",
            name="full_name_bangla",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="admission",
            name="full_name_english",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="admission",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="gpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="group",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="admission",
            name="guardian_mobile",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="admission",
            name="highest_exam",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="admission",
            name="mobile_student",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="admission",
            name="mother_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="admission",
            name="mother_nid",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="admission",
            name="passing_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="admission",
            name="permanent_address",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="admission",
            name="present_address",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="admission",
            name="registration_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="admission",
            name="roll_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="admission",
            name="session",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["is_draft"], name="admissions_is_draf_0bd161_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["user", "is_draft"], name="admissions_user_id_e15a08_idx"
            ),
        ),
    ]
