# Generated by Django 4.2.7 on 2025-12-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0003_admission_draft_data_admission_draft_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="document_processing_errors",
            field=models.JSONField(
                blank=True,
                help_text="Stores any errors that occurred during document processing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="documents_processed",
            field=models.BooleanField(
                default=False,
                help_text="True if all documents have been processed and saved",
            ),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["documents_processed"], name="admissions_documen_c3132f_idx"
            ),
        ),
    ]
