# Generated by Django 4.2.7 on 2026-07-14 17:33

import apps.admissions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0007_add_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='current_registration_number',
            field=models.CharField(blank=True, help_text='Existing college registration (optional); used as official reg if set', max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='current_roll_number',
            field=models.CharField(blank=True, help_text='Existing college roll (optional); used as official roll if set', max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='previous_gpas',
            field=models.JSONField(blank=True, default=list, help_text='Optional prior-semester GPAs for mid-programme admissions'),
        ),
        migrations.AddField(
            model_name='admission',
            name='semester',
            field=models.IntegerField(blank=True, help_text='Semester selected during admission (1-8). Blank on legacy rows.', null=True),
        ),
        migrations.CreateModel(
            name='AdmissionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admission_enabled', models.BooleanField(default=True, help_text='When off, hide Admission from students and refuse new submissions')),
                ('document_requirements', models.JSONField(blank=True, default=apps.admissions.models.default_document_requirements, help_text='Map of document field -> mandatory(bool)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_admission_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Settings',
                'verbose_name_plural': 'Admission Settings',
                'db_table': 'admission_settings',
            },
        ),
    ]
