# Generated by Django 4.2.7 on 2025-12-14 15:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the notice",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Content of the notice",
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        help_text="Priority level of the notice",
                        max_length=10,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the notice is published and visible to students",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the notice was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the notice was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin user who created the notice",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoticeReadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the notice was marked as read",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        help_text="The notice that was read",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_statuses",
                        to="notices.notice",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student who read the notice",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_read_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notice Read Status",
                "verbose_name_plural": "Notice Read Statuses",
                "ordering": ["-read_at"],
                "indexes": [
                    models.Index(
                        fields=["notice", "student"],
                        name="notices_not_notice__1d10f4_idx",
                    ),
                    models.Index(
                        fields=["student", "-read_at"],
                        name="notices_not_student_52adf7_idx",
                    ),
                    models.Index(
                        fields=["-read_at"], name="notices_not_read_at_4a790a_idx"
                    ),
                ],
                "unique_together": {("notice", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["-created_at"], name="notices_not_created_8044bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["is_published", "-created_at"],
                name="notices_not_is_publ_6fb610_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["priority", "-created_at"],
                name="notices_not_priorit_ff11af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["created_by"], name="notices_not_created_afbedd_idx"
            ),
        ),
    ]
