# Generated by Django 4.2.7 on 2026-06-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The attached file (image or PDF)', upload_to='notices/')),
                ('original_name', models.CharField(blank=True, help_text='Original filename as uploaded', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(help_text='The notice this file is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notices.notice')),
            ],
            options={
                'verbose_name': 'Notice Attachment',
                'verbose_name_plural': 'Notice Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
