# Generated by Django 4.2.7 on 2026-07-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_autoattendancesync'),
        ('notices', '0002_noticeattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone (Students + Teachers + Alumni)'), ('students_teachers', 'Active Students + Teachers'), ('students', 'Active Students Only'), ('teachers', 'Teachers Only'), ('alumni', 'Alumni Only')], default='students_teachers', help_text='Base recipient groups for this notice', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='recipient_count',
            field=models.PositiveIntegerField(blank=True, help_text='Recipient count computed when the notice was last saved', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_departments',
            field=models.ManyToManyField(blank=True, help_text='Restrict to these departments (empty = all departments)', related_name='targeted_notices', to='departments.department'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_semesters',
            field=models.JSONField(blank=True, default=list, help_text='Restrict students to these semesters (empty = all)'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_sessions',
            field=models.JSONField(blank=True, default=list, help_text='Restrict students/alumni to these sessions (empty = all)'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_shifts',
            field=models.JSONField(blank=True, default=list, help_text='Restrict students/alumni to these shifts (empty = all)'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['audience'], name='notices_not_audienc_def41a_idx'),
        ),
    ]
