# Generated by Django 4.2.7 on 2026-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_add_department_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='autoAttendanceSync',
            field=models.BooleanField(default=False),
        ),
    ]
