# Generated by Django 5.1.4 on 2026-01-22 09:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_hub', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('microsoft_teams', 'Microsoft Teams'), ('jitsi', 'Jitsi Meet'), ('webex', 'Cisco Webex'), ('other', 'Other')], default='zoom', max_length=20)),
                ('meeting_link', models.URLField()),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('passcode', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live Now'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('max_participants', models.IntegerField(default=100)),
                ('agenda', models.JSONField(blank=True, default=list)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notification_time', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='learning_hub.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'db_table': 'live_classes',
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recording_type', models.CharField(choices=[('full', 'Full Class Recording'), ('highlight', 'Highlight Reel'), ('segment', 'Class Segment'), ('audio', 'Audio Only')], default='full', max_length=20)),
                ('file_url', models.URLField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('chapters', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('password_protected', models.BooleanField(default=False)),
                ('access_password', models.CharField(blank=True, max_length=50)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='live_classes.liveclass')),
            ],
            options={
                'db_table': 'live_class_recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('poll_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('rating', 'Rating Scale'), ('open_text', 'Open Text')], default='multiple_choice', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('allow_multiple_answers', models.BooleanField(default=False)),
                ('time_limit_seconds', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='live_classes.liveclass')),
            ],
            options={
                'db_table': 'live_class_polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=255)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('guest', 'Guest')], default='student', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('is_present', models.BooleanField(default=False)),
                ('questions_asked', models.IntegerField(default=0)),
                ('chat_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live_classes.liveclass')),
            ],
            options={
                'db_table': 'live_class_participants',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('question', 'Question'), ('answer', 'Answer'), ('poll', 'Poll'), ('announcement', 'Announcement')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('reactions', models.JSONField(blank=True, default=dict)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='live_classes.classchat')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='live_classes.liveclass')),
            ],
            options={
                'db_table': 'live_class_chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('text_response', models.TextField(blank=True)),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='live_classes.classpoll')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'live_class_poll_responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('watch_duration_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_position_seconds', models.IntegerField(default=0)),
                ('bookmarks', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='live_classes.classrecording')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'live_class_recording_access',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['scheduled_date', 'status'], name='live_classe_schedul_dd72e2_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['subject'], name='live_classe_subject_dcc121_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['teacher'], name='live_classe_teacher_048b52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classparticipant',
            unique_together={('live_class', 'student'), ('live_class', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together={('poll', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='recordingaccess',
            unique_together={('recording', 'student')},
        ),
    ]
