# Generated by Django 5.1.4 on 2026-02-01 21:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the motivational message', max_length=200)),
                ('message', models.TextField(help_text='The motivational message content')),
                ('author', models.CharField(help_text='Author or source of the message', max_length=100)),
                ('category', models.CharField(choices=[('success', 'Success'), ('inspiration', 'Inspiration'), ('encouragement', 'Encouragement'), ('wisdom', 'Wisdom'), ('academic', 'Academic'), ('career', 'Career'), ('personal', 'Personal Development'), ('spiritual', 'Spiritual')], default='inspiration', max_length=20)),
                ('title_bn', models.CharField(blank=True, help_text='Title in Bengali', max_length=200, null=True)),
                ('message_bn', models.TextField(blank=True, help_text='Message in Bengali', null=True)),
                ('author_bn', models.CharField(blank=True, help_text='Author name in Bengali', max_length=100, null=True)),
                ('title_ar', models.CharField(blank=True, help_text='Title in Arabic', max_length=200, null=True)),
                ('message_ar', models.TextField(blank=True, help_text='Message in Arabic', null=True)),
                ('author_ar', models.CharField(blank=True, help_text='Author name in Arabic', max_length=100, null=True)),
                ('reference_source', models.CharField(blank=True, help_text='Source of the quote (book, speech, etc.)', max_length=200, null=True)),
                ('reference_url', models.URLField(blank=True, help_text='URL reference if available', null=True)),
                ('reference_date', models.DateField(blank=True, help_text='Date of the original quote/speech', null=True)),
                ('reference_context', models.TextField(blank=True, help_text='Context or background of the quote', null=True)),
                ('primary_language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali'), ('ar', 'Arabic'), ('ur', 'Urdu'), ('hi', 'Hindi')], default='en', max_length=5)),
                ('display_duration', models.IntegerField(choices=[(5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (30, '30 seconds'), (60, '1 minute'), (300, '5 minutes'), (600, '10 minutes'), (1800, '30 minutes'), (3600, '1 hour'), (86400, '1 day')], default=86400, help_text='How long to display this message before changing')),
                ('priority', models.IntegerField(default=1, help_text='Priority level (1-10, higher numbers shown more frequently)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this message is active')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured messages appear more frequently')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this message was viewed')),
                ('like_count', models.PositiveIntegerField(default=0, help_text='Number of likes from students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start showing this message', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing this message', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_motivations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_motivations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motivation Message',
                'verbose_name_plural': 'Motivation Messages',
                'db_table': 'motivation_messages',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotivationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='motivations.motivationmessage')),
            ],
            options={
                'verbose_name': 'Motivation Like',
                'verbose_name_plural': 'Motivation Likes',
                'db_table': 'motivation_likes',
            },
        ),
        migrations.CreateModel(
            name='MotivationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_display_duration', models.IntegerField(default=86400, help_text='Default display duration in seconds')),
                ('auto_rotate', models.BooleanField(default=True, help_text='Automatically rotate messages')),
                ('rotation_interval', models.IntegerField(default=3600, help_text='Rotation interval in seconds')),
                ('default_language', models.CharField(default='en', help_text='Default language for messages', max_length=5)),
                ('enable_multilingual', models.BooleanField(default=True, help_text='Enable multilingual support')),
                ('enable_likes', models.BooleanField(default=True, help_text='Allow students to like messages')),
                ('enable_analytics', models.BooleanField(default=True, help_text='Track views and analytics')),
                ('enable_scheduling', models.BooleanField(default=True, help_text='Enable message scheduling')),
                ('max_messages_per_day', models.IntegerField(default=5, help_text='Maximum messages to show per day')),
                ('prioritize_featured', models.BooleanField(default=True, help_text='Show featured messages more frequently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motivation Settings',
                'verbose_name_plural': 'Motivation Settings',
                'db_table': 'motivation_settings',
            },
        ),
        migrations.CreateModel(
            name='MotivationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('language_requested', models.CharField(default='en', max_length=5)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='motivations.motivationmessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motivation View',
                'verbose_name_plural': 'Motivation Views',
                'db_table': 'motivation_views',
            },
        ),
        migrations.AddIndex(
            model_name='motivationmessage',
            index=models.Index(fields=['is_active', 'priority'], name='motivation__is_acti_493373_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationmessage',
            index=models.Index(fields=['category', 'is_active'], name='motivation__categor_809317_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationmessage',
            index=models.Index(fields=['primary_language', 'is_active'], name='motivation__primary_b801de_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationmessage',
            index=models.Index(fields=['start_date', 'end_date'], name='motivation__start_d_785a27_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationlike',
            index=models.Index(fields=['message', 'created_at'], name='motivation__message_77d0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationlike',
            index=models.Index(fields=['user', 'created_at'], name='motivation__user_id_c0af1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='motivationlike',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='motivationview',
            index=models.Index(fields=['message', 'viewed_at'], name='motivation__message_91ef72_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationview',
            index=models.Index(fields=['user', 'viewed_at'], name='motivation__user_id_9bf7e9_idx'),
        ),
    ]
