# Generated by Django 4.2.7 on 2025-12-03 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="notificatio_notific_3e574c_idx",
            old_name="notifications_delivery_notif_channel_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="notificatio_status_350234_idx",
            old_name="notifications_delivery_status_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_a972ce_idx",
            old_name="notifications_recipient_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_e285de_idx",
            old_name="notifications_recipient_status_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_notific_f2898f_idx",
            old_name="notifications_type_idx",
        ),
    ]
