# Generated by Django 5.1.4 on 2026-02-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notifications_delivery_notif_channel_idx_notificatio_notific_3e574c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_status', 'Application Status'), ('document_approval', 'Document Approval'), ('student_admission', 'Student Admission'), ('system_announcement', 'System Announcement'), ('deadline_reminder', 'Deadline Reminder'), ('account_activity', 'Account Activity'), ('attendance_update', 'Attendance Update')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreferencetype',
            name='notification_type',
            field=models.CharField(choices=[('application_status', 'Application Status'), ('document_approval', 'Document Approval'), ('student_admission', 'Student Admission'), ('system_announcement', 'System Announcement'), ('deadline_reminder', 'Deadline Reminder'), ('account_activity', 'Account Activity'), ('attendance_update', 'Attendance Update')], max_length=50),
        ),
    ]
