# Generated by Django 4.2.7 on 2026-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_status', 'Application Status'), ('document_approval', 'Document Approval'), ('student_admission', 'Student Admission'), ('system_announcement', 'System Announcement'), ('deadline_reminder', 'Deadline Reminder'), ('account_activity', 'Account Activity'), ('attendance_update', 'Attendance Update'), ('welcome', 'Welcome'), ('teacher_request', 'Teacher Request'), ('signup_request', 'Signup Request'), ('notice_published', 'Notice Published'), ('class_routine', 'Class Routine'), ('admission_complete', 'Admission Complete'), ('application_submitted', 'Application Submitted'), ('security_alert', 'Security Alert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreferencetype',
            name='notification_type',
            field=models.CharField(choices=[('application_status', 'Application Status'), ('document_approval', 'Document Approval'), ('student_admission', 'Student Admission'), ('system_announcement', 'System Announcement'), ('deadline_reminder', 'Deadline Reminder'), ('account_activity', 'Account Activity'), ('attendance_update', 'Attendance Update'), ('welcome', 'Welcome'), ('teacher_request', 'Teacher Request'), ('signup_request', 'Signup Request'), ('notice_published', 'Notice Published'), ('class_routine', 'Class Routine'), ('admission_complete', 'Admission Complete'), ('application_submitted', 'Application Submitted'), ('security_alert', 'Security Alert')], max_length=50),
        ),
    ]
