#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# exam-reminder-timer.sh — install an HOURLY systemd timer that sends the
# automatic exam reminders (notification + email) to students:
#
#   countdown   from 30 days before a student's first exam, every 3 days
#   day_before  the day before each exam, with a preparation checklist
#   exam_day    ~3 hours before an exam starts ("get ready")
#
# The command is idempotent (every send is recorded in routine_reminder_log),
# so an hourly cadence never double-sends — it just catches each window.
#
# deploy.sh runs this automatically (setup_timers step), so a normal
# `sudo ./deploy.sh` already installs it. Run it directly only for a
# one-off install/uninstall without a full deploy:
#   sudo ./exam-reminder-timer.sh                 # install + enable
#   sudo ./exam-reminder-timer.sh --uninstall     # remove the timer
#
# One-off manual run (no timer needed):
#   cd server && ./venv/bin/python manage.py send_exam_reminders
#   cd server && ./venv/bin/python manage.py send_exam_reminders --dry-run
#
# Mirrors the sipi-purge.timer pattern in purge-timer.sh.
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_PATH="$(cd "${SCRIPT_DIR}/.." && pwd)"
SERVER_DIR="${PROJECT_PATH}/server"
VENV_DIR="${SERVER_DIR}/venv"
PYBIN="${VENV_DIR}/bin/python"

RUN_AS_USER="${RUN_AS_USER:-www-data}"
# Hourly at minute 05 by default; override with REMINDER_SCHEDULE.
REMINDER_SCHEDULE="${REMINDER_SCHEDULE:-*-*-* *:05:00}"
SYSTEMD_DIR="${SYSTEMD_DIR:-/etc/systemd/system}"

require_root() { [[ "${EUID}" -eq 0 ]] || { echo "Run as root (sudo)."; exit 1; }; }

uninstall() {
  require_root
  systemctl disable --now sipi-exam-reminders.timer 2>/dev/null || true
  rm -f "${SYSTEMD_DIR}/sipi-exam-reminders.timer" \
        "${SYSTEMD_DIR}/sipi-exam-reminders.service"
  systemctl daemon-reload
  echo "sipi-exam-reminders timer removed."
}

install() {
  require_root
  [[ -x "${PYBIN}" ]] || { echo "Missing venv python at ${PYBIN}"; exit 1; }

  cat > "${SYSTEMD_DIR}/sipi-exam-reminders.service" <<EOF
# GENERATED by exam-reminder-timer.sh
[Unit]
Description=SIPI — send automatic exam reminders to students
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
Type=oneshot
User=${RUN_AS_USER}
WorkingDirectory=${SERVER_DIR}
Environment=PYTHONUNBUFFERED=1
ExecStart=${PYBIN} manage.py send_exam_reminders
TimeoutStartSec=30m
EOF

  cat > "${SYSTEMD_DIR}/sipi-exam-reminders.timer" <<EOF
# GENERATED by exam-reminder-timer.sh
[Unit]
Description=Run SIPI exam reminders hourly

[Timer]
OnCalendar=${REMINDER_SCHEDULE}
RandomizedDelaySec=120
Persistent=true

[Install]
WantedBy=timers.target
EOF

  systemctl daemon-reload
  systemctl enable --now sipi-exam-reminders.timer
  echo "Hourly exam-reminder timer installed: ${REMINDER_SCHEDULE}"
  systemctl list-timers sipi-exam-reminders.timer --no-pager || true
}

case "${1:-}" in
  --uninstall) uninstall ;;
  *)           install ;;
esac
