#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# purge-timer.sh — install a daily systemd timer that permanently removes
# students whose 7-day "Delete Account" recovery window has elapsed.
#
# The admin "Delete Account" action only SCHEDULES a deletion (soft-delete with
# a 7-day recovery window; a student login auto-cancels it). This timer runs
# `manage.py purge_pending_deletions` once a day to hard-delete the ones that
# expired. Without it, expired accounts are never actually purged.
#
# Usage (on the server, as root):
#   sudo ./purge-timer.sh                 # install + enable the daily timer
#   sudo ./purge-timer.sh --uninstall     # remove the timer
#
# One-off manual run (no timer needed):
#   cd server && ./venv/bin/python manage.py purge_pending_deletions
#   cd server && ./venv/bin/python manage.py purge_pending_deletions --dry-run
#
# Mirrors the sipi-backup.timer pattern in backup.sh.
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_PATH="$(cd "${SCRIPT_DIR}/.." && pwd)"
SERVER_DIR="${PROJECT_PATH}/server"
VENV_DIR="${SERVER_DIR}/venv"
PYBIN="${VENV_DIR}/bin/python"

# Run the purge as the same unprivileged user that owns the app (override with
# RUN_AS_USER=... if your deploy uses a different account).
RUN_AS_USER="${RUN_AS_USER:-www-data}"
# Daily at 03:30 by default; override with PURGE_SCHEDULE (systemd OnCalendar).
PURGE_SCHEDULE="${PURGE_SCHEDULE:-*-*-* 03:30:00}"
SYSTEMD_DIR="${SYSTEMD_DIR:-/etc/systemd/system}"

require_root() { [[ "${EUID}" -eq 0 ]] || { echo "Run as root (sudo)."; exit 1; }; }

uninstall() {
  require_root
  systemctl disable --now sipi-purge.timer 2>/dev/null || true
  rm -f "${SYSTEMD_DIR}/sipi-purge.timer" "${SYSTEMD_DIR}/sipi-purge.service"
  systemctl daemon-reload
  echo "sipi-purge timer removed."
}

install() {
  require_root
  [[ -x "${PYBIN}" ]] || { echo "Missing venv python at ${PYBIN}"; exit 1; }

  cat > "${SYSTEMD_DIR}/sipi-purge.service" <<EOF
# GENERATED by purge-timer.sh
[Unit]
Description=SIPI — purge students past their deletion recovery window
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
Type=oneshot
User=${RUN_AS_USER}
WorkingDirectory=${SERVER_DIR}
Environment=PYTHONUNBUFFERED=1
ExecStart=${PYBIN} manage.py purge_pending_deletions
TimeoutStartSec=30m
EOF

  cat > "${SYSTEMD_DIR}/sipi-purge.timer" <<EOF
# GENERATED by purge-timer.sh
[Unit]
Description=Run SIPI student-deletion purge daily

[Timer]
OnCalendar=${PURGE_SCHEDULE}
RandomizedDelaySec=300
Persistent=true

[Install]
WantedBy=timers.target
EOF

  systemctl daemon-reload
  systemctl enable --now sipi-purge.timer
  echo "Daily purge timer installed: ${PURGE_SCHEDULE}"
  systemctl list-timers sipi-purge.timer --no-pager || true
}

case "${1:-}" in
  --uninstall) uninstall ;;
  *)           install ;;
esac
