# Generated by Django 4.2.7 on 2025-12-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("mobile_number", models.CharField(blank=True, max_length=11)),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("registrar", "Registrar"),
                            ("institute_head", "Institute Head"),
                        ],
                        max_length=20,
                    ),
                ),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signup_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_signup_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signup Request",
                "verbose_name_plural": "Signup Requests",
                "db_table": "auth_signup_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="auth_signup_status_713104_idx"
                    ),
                    models.Index(
                        fields=["username"], name="auth_signup_usernam_455be7_idx"
                    ),
                    models.Index(fields=["email"], name="auth_signup_email_35ac55_idx"),
                    models.Index(
                        fields=["created_at"], name="auth_signup_created_9759b3_idx"
                    ),
                ],
            },
        ),
    ]
