# Generated by Django 4.2.7 on 2026-01-31 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_signuprequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Password Reset Attempt",
                "verbose_name_plural": "Password Reset Attempts",
                "db_table": "auth_password_reset_attempt",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="auth_passwo_email_3a0594_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="auth_passwo_ip_addr_527fd3_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="auth_passwo_created_68f427_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OTPToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Token",
                "verbose_name_plural": "OTP Tokens",
                "db_table": "auth_otp_token",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="auth_otp_to_user_id_545f28_idx",
                    ),
                    models.Index(fields=["token"], name="auth_otp_to_token_b81b9b_idx"),
                    models.Index(
                        fields=["expires_at"], name="auth_otp_to_expires_78de31_idx"
                    ),
                    models.Index(
                        fields=["is_used"], name="auth_otp_to_is_used_1414b4_idx"
                    ),
                ],
            },
        ),
    ]
