# Generated by Django 4.2.7 on 2026-02-26 19:24

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_fix_superuser_roles"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.authentication.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
