# Generated by Django 4.2.7 on 2026-06-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_add_department_fields'),
        ('authentication', '0007_user_interface_mode_rbac_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to='departments.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this Department Head manages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads', to='departments.department'),
        ),
    ]
