# Generated by Django 4.2.7 on 2026-06-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_signuprequest_department_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo / avatar', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Require an email OTP code at login'),
        ),
    ]
