# Generated by Django 4.2.7 on 2026-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_profile_photo_user_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature image used on approved documents', null=True, upload_to='signatures/'),
        ),
    ]
