# Generated by Django 4.2.7 on 2026-06-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_alumni_account',
            field=models.BooleanField(default=False, help_text='True for accounts that registered as Alumni (self-registration flow)'),
        ),
    ]
