# Generated by Django 4.2.7 on 2026-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_is_alumni_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='shift',
            field=models.CharField(blank=True, choices=[('1st_shift', '1st Shift'), ('2nd_shift', '2nd Shift')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, choices=[('1st_shift', '1st Shift'), ('2nd_shift', '2nd Shift')], help_text='Shift managed by a Department Head', max_length=20),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
