# Generated by Django 4.2.7 on 2026-07-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_signuprequest_shift_user_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Receive non-OTP notification emails (OTP emails are always sent)'),
        ),
    ]
