# Generated by Django 4.2.7 on 2026-07-04 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_autoattendancesync'),
        ('authentication', '0014_user_email_notifications_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainAccountRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_requests', to='departments.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_captain_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Captain Account Request',
                'verbose_name_plural': 'Captain Account Requests',
                'db_table': 'auth_captain_account_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='auth_captai_status_be1afb_idx'), models.Index(fields=['department', 'shift', 'status'], name='auth_captai_departm_1fb129_idx')],
            },
        ),
    ]
