# Generated by Django 4.2.7 on 2026-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_captainaccountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alumni_visible',
            field=models.BooleanField(default=True),
        ),
    ]
