# Generated by Django 4.2.7 on 2025-12-01 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=255)),
                ('fileType', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('NID', 'National ID'), ('Birth Certificate', 'Birth Certificate'), ('Marksheet', 'Marksheet'), ('Certificate', 'Certificate'), ('Testimonial', 'Testimonial'), ('Photo', 'Photo'), ('Other', 'Other')], default='Other', max_length=50)),
                ('filePath', models.CharField(max_length=500)),
                ('fileSize', models.IntegerField()),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploadDate'],
                'indexes': [models.Index(fields=['student'], name='documents_student_c9b435_idx'), models.Index(fields=['category'], name='documents_categor_f8ad6f_idx'), models.Index(fields=['uploadDate'], name='documents_uploadD_5e9f3d_idx')],
            },
        ),
    ]
