# Generated by Django 4.2.7 on 2025-12-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_field_name",
            field=models.CharField(
                blank=True,
                help_text="Original field name from admission form (e.g., 'photo', 'sscMarksheet')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID of the source record (e.g., admission ID)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("admission", "Admission Upload"),
                    ("manual", "Manual Upload"),
                ],
                default="manual",
                help_text="Source of the document upload",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["source_type"], name="documents_source__4f562e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["source_id"], name="documents_source__ea06cc_idx"
            ),
        ),
    ]
