# Generated by Django 4.2.7 on 2025-12-15 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
        ("documents", "0002_document_original_field_name_document_source_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="students.student",
            ),
        ),
    ]
