# Generated by Django 5.1.4 on 2026-02-01 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_student'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('upload', 'Upload'), ('delete', 'Delete'), ('modify', 'Modify')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'document_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='access_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Custom access permissions'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Document description'),
        ),
        migrations.AddField(
            model_name='document',
            name='fileHash',
            field=models.CharField(blank=True, help_text='SHA256 hash for integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether file can be accessed without authentication'),
        ),
        migrations.AddField(
            model_name='document',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AddField(
            model_name='document',
            name='mimeType',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('corrupted', 'Corrupted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorization and search'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('NID', 'National ID'), ('Birth Certificate', 'Birth Certificate'), ('Marksheet', 'Marksheet'), ('Certificate', 'Certificate'), ('Testimonial', 'Testimonial'), ('Photo', 'Photo'), ('Medical Certificate', 'Medical Certificate'), ('Quota Document', 'Quota Document'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='fileName',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='filePath',
            field=models.CharField(help_text='Relative path to file in storage system', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='fileSize',
            field=models.BigIntegerField(help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fileType',
            field=models.CharField(help_text="File extension (e.g., 'pdf', 'jpg')", max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_field_name',
            field=models.CharField(blank=True, help_text='Original field name from admission form', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('admission', 'Admission Upload'), ('manual', 'Manual Upload'), ('system', 'System Generated')], default='manual', help_text='Source of the document upload', max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_status_f31a08_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['fileHash'], name='documents_fileHas_69cd9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('fileSize__gte', 0)), name='positive_file_size'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['document'], name='document_ac_documen_abedbb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['user'], name='document_ac_user_id_4e9656_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['timestamp'], name='document_ac_timesta_36fb31_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['access_type'], name='document_ac_access__040168_idx'),
        ),
    ]
