# Generated by Django 5.1.4 on 2026-02-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_year_type_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='doc_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='doc_year_type_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, help_text='Year for partitioning (extracted from uploadDate)', null=True),
        ),
    ]
