# Generated by Django 4.2.7 on 2026-06-28 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_document_doc_year_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('testimonial', 'Testimonial'), ('certificate', 'Certificate'), ('transcript', 'Transcript'), ('character', 'Character Certificate'), ('clearance', 'Clearance Certificate'), ('bonafide', 'Bonafide Certificate'), ('eligibility', 'Eligibility Statement'), ('completion', 'Certificate of Completion'), ('idCard', 'ID Card'), ('other', 'Other')], default='other', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True, help_text='Template HTML with [Token] and [SIG_*] markers')),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('available_to_students', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'db_table': 'document_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='document_te_slug_65c77a_idx'), models.Index(fields=['available_to_students', 'is_active'], name='document_te_availab_c70739_idx')],
            },
        ),
    ]
