# Generated by Django 4.2.7 on 2025-12-01 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='alumni', serialize=False, to='students.student')),
                ('alumniType', models.CharField(choices=[('recent', 'Recent Graduate'), ('established', 'Established Professional')], default='recent', max_length=20)),
                ('transitionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('graduationYear', models.IntegerField()),
                ('currentSupportCategory', models.CharField(choices=[('receiving_support', 'Receiving Support'), ('needs_extra_support', 'Needs Extra Support'), ('no_support_needed', 'No Support Needed')], default='no_support_needed', max_length=30)),
                ('currentPosition', models.JSONField(blank=True, null=True)),
                ('careerHistory', models.JSONField(blank=True, default=list)),
                ('supportHistory', models.JSONField(blank=True, default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
                'db_table': 'alumni',
                'ordering': ['-transitionDate'],
                'indexes': [models.Index(fields=['alumniType'], name='alumni_alumniT_95d2f5_idx'), models.Index(fields=['graduationYear'], name='alumni_graduat_434696_idx'), models.Index(fields=['currentSupportCategory'], name='alumni_current_d581a2_idx')],
            },
        ),
    ]
