# Generated by Django 4.2.7 on 2025-12-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumni",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumni",
            name="highlights",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="alumni",
            name="linkedinUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumni",
            name="portfolioUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumni",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
