# Generated by Django 5.1.4 on 2026-02-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumni_bio_alumni_highlights_alumni_linkedinurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='courses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
