# Generated by Django 5.1.4 on 2026-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumni_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='isVerified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='lastEditedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='lastEditedBy',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='alumni',
            name='verificationNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
