# Generated by Django 4.2.7 on 2026-06-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alumni_isverified_alumni_lasteditedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='registrationSource',
            field=models.CharField(choices=[('pipeline', 'Promoted From Student'), ('admin_manual', 'Manually Added By Admin'), ('self_registration', 'Self Registered')], default='pipeline', max_length=20),
        ),
        migrations.AddField(
            model_name='alumni',
            name='reviewStatus',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='graduationYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['registrationSource'], name='alumni_registr_f61fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['reviewStatus'], name='alumni_reviewS_bf0501_idx'),
        ),
    ]
