# Generated by Django 4.2.7 on 2026-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alumni_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='registrationSource',
            field=models.CharField(choices=[('pipeline', 'Promoted From Student'), ('admin_manual', 'Manually Added By Admin'), ('self_registration', 'Self Registered'), ('student_prefill', 'Student Pre-fill (Not Alumni)')], default='pipeline', max_length=20),
        ),
    ]
