# Generated by Django 4.2.7 on 2025-12-01 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullNameBangla', models.CharField(max_length=255)),
                ('fullNameEnglish', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('motherName', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=20)),
                ('shift', models.CharField(max_length=20)),
                ('rollNumber', models.CharField(max_length=50)),
                ('registrationNumber', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('applicationType', models.CharField(choices=[('Testimonial', 'Testimonial'), ('Certificate', 'Certificate'), ('Transcript', 'Transcript'), ('Stipend', 'Stipend'), ('Transfer', 'Transfer Certificate'), ('Other', 'Other')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('reviewedBy', models.CharField(blank=True, max_length=255)),
                ('reviewNotes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-submittedAt'],
                'indexes': [models.Index(fields=['status'], name='application_status_e61111_idx'), models.Index(fields=['applicationType'], name='application_applica_b717f8_idx'), models.Index(fields=['submittedAt'], name='application_submitt_375a29_idx')],
            },
        ),
    ]
