# Generated by Django 4.2.7 on 2025-12-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="selectedDocuments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
