# Generated by Django 4.2.7 on 2026-06-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_add_department_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0009_documenttemplate'),
        ('students', '0002_add_nationality_field'),
        ('applications', '0002_application_selecteddocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approver_role', models.CharField(blank=True, max_length=20)),
                ('approver_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('forwarded', 'Forwarded'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('forwarded_to_role', models.CharField(blank=True, max_length=20)),
                ('forwarded_to_name', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Approval',
                'verbose_name_plural': 'Application Approvals',
                'db_table': 'application_approvals',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='current_approver',
            field=models.ForeignKey(blank=True, help_text='Specific approver (set when assigned to a particular Department Head)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='current_approver_role',
            field=models.CharField(blank=True, choices=[('registrar', 'Registrar'), ('institute_head', 'Principal'), ('department_head', 'Department Head')], default='registrar', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='current_department',
            field=models.ForeignKey(blank=True, help_text='Department whose head should review (when assigned to a Department Head)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_applications', to='departments.department'),
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = first approver, 2 = forwarded approver'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='students.student'),
        ),
        migrations.AddField(
            model_name='application',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='documents.documenttemplate'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['current_approver_role'], name='application_current_870d48_idx'),
        ),
        migrations.AddField(
            model_name='applicationapproval',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationapproval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='applicationapproval',
            index=models.Index(fields=['application', 'order'], name='application_applica_35f9e7_idx'),
        ),
    ]
