# Generated by Django 4.2.7 on 2025-12-08 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fullNameBangla", models.CharField(max_length=255)),
                ("fullNameEnglish", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=100)),
                ("subjects", models.JSONField(default=list)),
                ("qualifications", models.JSONField(default=list)),
                ("specializations", models.JSONField(default=list)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobileNumber", models.CharField(max_length=11)),
                ("officeLocation", models.CharField(max_length=255)),
                (
                    "employmentStatus",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joiningDate", models.DateField()),
                ("profilePhoto", models.CharField(blank=True, max_length=500)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teachers",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "db_table": "teachers",
                "ordering": ["fullNameEnglish"],
                "indexes": [
                    models.Index(fields=["email"], name="teachers_email_87e41d_idx"),
                    models.Index(
                        fields=["employmentStatus"], name="teachers_employm_e8abe6_idx"
                    ),
                    models.Index(
                        fields=["department"], name="teachers_departm_02fbe9_idx"
                    ),
                ],
            },
        ),
    ]
