# Generated by Django 5.1.4 on 2026-02-21 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_add_shifts_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='coverPhoto',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='headline',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeacherAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Award',
                'verbose_name_plural': 'Teacher Awards',
                'db_table': 'teacher_awards',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='TeacherEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('field', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Education',
                'verbose_name_plural': 'Teacher Education',
                'db_table': 'teacher_education',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='TeacherExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('startDate', models.CharField(max_length=50)),
                ('endDate', models.CharField(blank=True, max_length=50)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Experience',
                'verbose_name_plural': 'Teacher Experiences',
                'db_table': 'teacher_experiences',
                'ordering': ['order', '-startDate'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('citations', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Publication',
                'verbose_name_plural': 'Teacher Publications',
                'db_table': 'teacher_publications',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='TeacherResearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('year', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Research',
                'verbose_name_plural': 'Teacher Research',
                'db_table': 'teacher_research',
                'ordering': ['order', '-year'],
            },
        ),
    ]
