# Generated by Django 4.2.7 on 2026-06-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_add_department_fields'),
        ('teachers', '0003_teacher_about_teacher_coverphoto_teacher_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='departments.department'),
        ),
    ]
