# Generated by Django 4.2.7 on 2026-07-02 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('bug', 'System Bug'), ('runtime_error', 'Runtime Error'), ('exception', 'Application Exception'), ('server_error', 'Server Error'), ('database_error', 'Database Error'), ('api_error', 'API Error'), ('background_job', 'Background Job Failure'), ('scheduled_task', 'Scheduled Task Failure'), ('email_failure', 'Email Delivery Failure'), ('file_storage', 'File Upload / Storage Error'), ('auth_failure', 'Authentication & Authorization'), ('performance', 'Performance Issue'), ('resource_alert', 'High Memory / CPU Alert'), ('slow_query', 'Slow Database Query'), ('network', 'Network Connectivity'), ('downtime', 'Service Downtime'), ('outage', 'System Outage'), ('maintenance', 'Maintenance Log'), ('security_alert', 'Security Alert'), ('audit', 'Audit Log'), ('crash', 'Crash Report')], default='exception', max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=15)),
                ('source', models.CharField(choices=[('auto_middleware', 'Auto: Request Middleware'), ('auto_logging', 'Auto: Error Logging'), ('auto_signal', 'Auto: System Signal'), ('health_monitor', 'Auto: Health Monitor'), ('manual', 'Manual Entry')], default='auto_middleware', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('exception_type', models.CharField(blank=True, max_length=255)),
                ('stack_trace', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_display', models.CharField(blank=True, max_length=150)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_system_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_system_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Report',
                'verbose_name_plural': 'System Reports',
                'db_table': 'system_reports',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['category', '-last_seen'], name='system_repo_categor_e634ad_idx'), models.Index(fields=['severity', '-last_seen'], name='system_repo_severit_875534_idx'), models.Index(fields=['status', '-last_seen'], name='system_repo_status_e97adf_idx'), models.Index(fields=['-last_seen'], name='system_repo_last_se_17c413_idx')],
            },
        ),
    ]
