# Generated by Django 4.2.7 on 2025-12-09 16:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarksRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_code", models.CharField(max_length=50)),
                ("subject_name", models.CharField(max_length=255)),
                (
                    "semester",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ]
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("midterm", "Midterm"),
                            ("final", "Final"),
                            ("assignment", "Assignment"),
                            ("practical", "Practical"),
                            ("quiz", "Quiz"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marks Record",
                "verbose_name_plural": "Marks Records",
                "db_table": "marks_records",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "subject_code"],
                        name="marks_recor_student_3696ef_idx",
                    ),
                    models.Index(
                        fields=["semester"], name="marks_recor_semeste_2dafc5_idx"
                    ),
                    models.Index(
                        fields=["exam_type"], name="marks_recor_exam_ty_c99d4c_idx"
                    ),
                ],
            },
        ),
    ]
