# Generated by Django 4.2.7 on 2025-12-14 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marksrecord",
            name="exam_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("midterm", "Midterm"),
                    ("final", "Final"),
                    ("assignment", "Assignment"),
                    ("practical", "Practical"),
                    ("quiz", "Quiz"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="marksrecord",
            name="marks_obtained",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="marksrecord",
            name="semester",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marksrecord",
            name="subject_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="marksrecord",
            name="subject_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="marksrecord",
            name="total_marks",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
