# Generated by Django 4.2.7 on 2026-07-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_routines', '0003_semesterarchive_and_more'),
        ('marks', '0002_alter_marksrecord_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksrecord',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_records', to='class_routines.semesterarchive'),
        ),
        migrations.AddIndex(
            model_name='marksrecord',
            index=models.Index(fields=['archive'], name='marks_recor_archive_796502_idx'),
        ),
    ]
