# Generated by Django 4.2.7 on 2025-12-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
