# Generated by Django 4.2.7 on 2025-12-08 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_academic_year",
                    models.CharField(default="2024-2025", max_length=20),
                ),
                ("current_semester", models.IntegerField(default=1)),
                ("enable_email_notifications", models.BooleanField(default=True)),
                ("enable_sms_notifications", models.BooleanField(default=False)),
                (
                    "admin_notification_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("allow_student_registration", models.BooleanField(default=True)),
                ("allow_teacher_registration", models.BooleanField(default=True)),
                ("allow_admission_submission", models.BooleanField(default=True)),
                (
                    "institute_name",
                    models.CharField(default="Institute Name", max_length=255),
                ),
                ("institute_address", models.TextField(blank=True)),
                ("institute_phone", models.CharField(blank=True, max_length=20)),
                ("institute_email", models.EmailField(blank=True, max_length=254)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
    ]
