# Generated by Django 4.2.7 on 2026-06-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_initialize_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='institute_logo',
            field=models.ImageField(blank=True, null=True, upload_to='institute/'),
        ),
    ]
