# Generated by Django 4.2.7 on 2026-07-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_systemsettings_institute_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_notice_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_notice_text',
            field=models.TextField(blank=True),
        ),
    ]
