# Generated by Django 4.2.7 on 2026-07-22 16:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=255)),
                ('fileSha256', models.CharField(max_length=64, unique=True)),
                ('pageCount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('examType', models.CharField(choices=[('final', 'Semester Final'), ('mid', 'Mid')], default='final', max_length=10)),
                ('regulationYear', models.IntegerField(blank=True, null=True)),
                ('examSession', models.CharField(blank=True, max_length=160)),
                ('memoNo', models.CharField(blank=True, max_length=100)),
                ('publicationDate', models.DateField(blank=True, null=True)),
                ('examStartDate', models.DateField(blank=True, null=True)),
                ('examEndDate', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('errorMessage', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('uploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routine_imports',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='RoutineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('theory', 'Theory (written)'), ('practical', 'Practical')], default='theory', max_length=12)),
                ('examDate', models.DateField()),
                ('weekday', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('other', 'Other')], default='morning', max_length=10)),
                ('startTime', models.TimeField()),
                ('durationMinutes', models.IntegerField(default=180)),
                ('poboLabel', models.CharField(blank=True, max_length=120)),
                ('regulationYear', models.IntegerField(blank=True, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='routines.routineimport')),
            ],
            options={
                'db_table': 'routine_sessions',
                'ordering': ['examDate', 'startTime'],
            },
        ),
        migrations.CreateModel(
            name='RoutineParserIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('stage', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='routines.routineimport')),
            ],
            options={
                'db_table': 'routine_parser_issues',
                'ordering': ['severity', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoutineSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectCode', models.CharField(max_length=10)),
                ('rawName', models.CharField(blank=True, max_length=255)),
                ('techApplicability', models.TextField(blank=True)),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='routines.routinesession')),
            ],
            options={
                'db_table': 'routine_subjects',
                'ordering': ['session', 'serial'],
                'indexes': [models.Index(fields=['subjectCode'], name='routine_sub_subject_c93df3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='routinesession',
            index=models.Index(fields=['routine', 'examDate'], name='routine_ses_routine_2feea8_idx'),
        ),
        migrations.AddIndex(
            model_name='routineparserissue',
            index=models.Index(fields=['routine', 'severity'], name='routine_par_routine_4b24b1_idx'),
        ),
    ]
