# Generated by Django 4.2.7 on 2026-07-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_publicprofileenabled'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('countdown', 'Countdown'), ('day_before', 'Day Before'), ('exam_day', 'Exam Day')], max_length=12)),
                ('subjectCode', models.CharField(blank=True, default='', max_length=10)),
                ('examDate', models.DateField(blank=True, null=True)),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remindersSent', to='routines.routineimport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReminders', to='students.student')),
            ],
            options={
                'db_table': 'routine_reminder_log',
                'indexes': [models.Index(fields=['student', 'kind', 'sentAt'], name='routine_rem_student_ecb754_idx'), models.Index(fields=['kind', 'examDate'], name='routine_rem_kind_9f3aef_idx')],
            },
        ),
    ]
